---
  
development: &defaults
  adapter:  mysql
  database: flurish_development
  username: flurish 
  password: 0vergr0wth
  host: getflurish.com
  port: 3306

test:
  adapter:  mysql
  database: flurish_test
  username: flurish
  password: 0vergr0wth
  host: getflurish.com
  port: 3306
 
production:
  adapter:  mysql
  database: flurish_production
  username: flurish
  password: 0vergr0wth
  host: getflurish.com
  port: 3306
 
rake:
  <<:   *defaults
